apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mysql-kafka-connector
  labels:
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: mysql-kafka-connect
spec:
  autoRestart:
    enabled: true
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: "10.96.107.175"
    database.port: "3306"
    database.user: "cdc_user"
    database.password: "cdc_password"
    topic.prefix: "cdc_db"
    database.server.id: "1"
    database.server.name: "cdc_db"
    database.include.list: "cdc_db"
    database.history.kafka.bootstrap.servers: "kakfa-data-platform-kafka-bootstrap.kafka.svc.cluster.local:9092"
    database.history.kafka.topic: "cdc_db.history"
    include.schema.changes: "true" 
    schema.history.internal.kafka.topic: "cdc_db.schema_history"
    schema.history.internal.kafka.bootstrap.servers: "kakfa-data-platform-kafka-bootstrap.kafka.svc.cluster.local:9092"
